### ISSUE TITLE
Keyword documentation is not correct

### ISSUE THREAD

**Issue by aaltat** [Altran-PT-GDC/Robot-Framework-Test-FX-Library#2]
1) The https://cdn.rawgit.com/Altran-PT-GDC/Robot-Framework-Test-FX-Library/585ec941/docs/TestFXLibrary.html#Click%20On%20Nth%20Component arguments column says that it takes only one argument, but the documentation says that there are two arguments. Which one is correct?
2) The https://cdn.rawgit.com/Altran-PT-GDC/Robot-Framework-Test-FX-Library/585ec941/docs/TestFXLibrary.html#Click%20On%20Component arguments column says that argument is a *varargs, but documentation says that keyword has an single argument. Which one is correct?

**Comment by jdagomes** [comment]
Thank you for your support.

The "Click On Component" keyword should have only one argument, and the "Click On Nth Component" should have two.

We will fix this issue in the next commits and mark this issue as resolved as soon as it is fixed.

**Comment by jdagomes** [comment]
The documentation for "Click On Component" keyword was updated.

Also removed the unnecessary "Click On Nth Component", because in the latest changes of "Click On Component" it was added the possibility to find an element by index.

Ex.: Click On Component    Button[2]

For more information about this topic check [Identifying Locators](https://github.com/Altran-PT-GDC/Robot-Framework-Test-FX-Library/wiki/5.-Identifying-Locators).

Thank you for your support.

I am going to mark this issue as resolved

**Comment by aaltat** [comment]
Glad to help.
